#pragma once

#define I2C1_SCL_PIN GP3
#define I2C1_SDA_PIN GP2
#define I2C_DRIVER I2CD1
#define OLED_HEIGHT 128
#define OLED_WIDTH 32

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 200U
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17

#define QUANTUM_PAINTER_DISPLAY_TIMEOUT 30000

#define RGB_MATRIX_SLEEP                    // turn off effects when suspended
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 200
